guest_list = ["Albert Einstein", "Richard Feynman", "Niels Bohr"]
print(f"You've been invited to the dinner, {guest_list[0]} ")
print(f"You've been invited to the dinner, {guest_list[1]} ")
print(f"You've been invited to the dinner, {guest_list[2]} ")
print(f"{guest_list[2]} can't make it.")
print("\n")
guest_list[2] = "Ernest Rutherford"
print(f"You've been invited to the dinner, {guest_list[0]} ")
print(f"You've been invited to the dinner, {guest_list[1]} ")
print(f"You've been invited to the dinner, {guest_list[2]} ")
print(f"I found a bigger dinner table, {guest_list[0]}, {guest_list[1]}, {guest_list[2]}")
print("\n")
guest_list.insert(0, "Michael Faraday")
guest_list.insert(3, "Isaac Newton")
guest_list.append("Galileo Galilei") #or guest_list.insert(6, "Galileo Galilei")
print(f"You've been invited to the dinner, {guest_list[0]} ")
print(f"You've been invited to the dinner, {guest_list[1]} ")
print(f"You've been invited to the dinner, {guest_list[2]} ")
print(f"You've been invited to the dinner, {guest_list[3]} ")
print(f"You've been invited to the dinner, {guest_list[4]} ")
print(f"You've been invited to the dinner, {guest_list[5]} ")
print("Sorry, I can invite only 2 guests!")
print("\n")
print(f"Sorry I can't invite you, dear {guest_list.pop()}")
print(f"Sorry I can't invite you, dear {guest_list.pop()}")
print(f"Sorry I can't invite you, dear {guest_list.pop()}")
print(f"Sorry I can't invite you, dear {guest_list.pop()}")
print(f"Dear {guest_list[0]}, you're still invited! ")
print(f"Dear {guest_list[1]}, you're still invited! ")
del guest_list[1]
del guest_list[0]
print(guest_list)
